language: php
cache:
  bundler: true
  apt: true
php:
  - 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
before_install:
- sudo apt-get update > /dev/null
- composer selfupdate
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
install:
- composer global require drush/drush:dev-master
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- git clone --branch 8.x-1.x http://git.drupal.org/project/composer.git ~/.drush/composer
- cd ..
- drush make --concurrency=5 drupal-org-core.make drupal -y
- mkdir drupal/profiles/quartz
- cp -R quartz/* drupal/profiles/quartz/.
- cd drupal
- drush make --concurrency=5 profiles/quartz/drupal-org.make --no-core --contrib-destination=profiles/quartz -y
before_script:
- drush si quartz --db-url=mysql://root:@localhost/drupal -y 
- drush cache-rebuild
- drush runserver --server=builtin 8080 &
- until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.2; done
script:
- cd core
- ./vendor/phpunit/phpunit/phpunit --verbose
matrix:
  fast_finish: true
